
---
title: "Lab 3 Revised: Regression Competition"
subtitle: "In the hot New Jersey night"
author: "Group A: Alice Chang, Isidore Weis, Sarah Maebius"
output: pdf_document

---

* * *

## Fit Model and Calculate MSE
```{r}
library(dplyr)
library(MASS)
d <- read.csv("http://andrewpbray.github.io/data/crime-train.csv")

d_cleaned <- data.frame("blank" = rep(0, nrow(d)))
counter <- 1

for(i in 5:ncol(d)){
  if(d[1, i] != "?"){
    d_cleaned[[counter]] <- d[[i]]
    colnames(d_cleaned)[counter] <- colnames(d)[i]
    counter <- counter + 1
  }
}

group_A_automated_fit<- function(training_data) {

m1 <- lm(ViolentCrimesPerPop ~   racePctWhite + racePctHisp + pctWSocSec + indianPerCap + PctLess9thGrade + PctNotHSGrad + PctEmploy + PctEmplProfServ + MalePctDivorce + FemalePctDiv + PctWorkMom + PctIlleg + PctImmigRec5 + PctImmigRec8 + PctImmigRec10 + PctVacantBoarded + PctVacMore6Mos + PctHousNoPhone + MedRent + MedRentPctHousInc + RentLowQ + MedOwnCostPctIncNoMtg + NumStreet + pctUrban + PctHousOccup, d_cleaned)
m1
}



group_A_process <- function(training_data) {
  training_data %>%
  mutate(sqrtcrime = sqrt(ViolentCrimesPerPop))
}


group_A_automated_fit(d_cleaned)

group_A_MSE <- function(model, data) {
  group_A_process(data)
  MSE <- mean(data$ViolentCrimesPerPop - predict(model, data)^2)
  MSE
}
group_A_MSE(m1, d_cleaned)






```

#### Forward Selection
```{r}

r1 <- regsubsets(ViolentCrimesPerPop ~ ., data = d_cleaned, nvmax = 25, method = "forward")

r1
attributes(r1)
str(r1)
plot(r1, scale = "adjr2", main = "Adjusted R^2")

summary.out <- summary(r1)
as.data.frame(summary.out$outmat)

which.max(summary.out$adjr2)
summary.out$which[25,]




best.model <- lm(ViolentCrimesPerPop ~   racePctWhite + racePctHisp + pctWSocSec + indianPerCap + PctLess9thGrade + PctNotHSGrad + PctEmploy + PctEmplProfServ + MalePctDivorce + FemalePctDiv + PctWorkMom + PctIlleg + PctImmigRec5 + PctImmigRec8 + PctImmigRec10 + PctVacantBoarded + PctVacMore6Mos + PctHousNoPhone + MedRent + MedRentPctHousInc + RentLowQ + MedOwnCostPctIncNoMtg + NumStreet + pctUrban + PctHousOccup, d_cleaned)



summary(best.model)



```
sesresr
### Backward Selection
```{r}
r2 <- regsubsets(ViolentCrimesPerPop ~ ., data = d_cleaned, nvmax = 25, method = "backward")

r2
attributes(r2)
str(r2)
plot(r2, scale = "adjr2", main = "Adjusted R^2")

summary2.out <- summary(r2)
as.data.frame(summary2.out$outmat)

which.max(summary2.out$adjr2)
summary2.out$which[25,]


best.model2 <- lm(ViolentCrimesPerPop ~ population + householdsize + racePctWhite + numbUrban + medIncome + medFamInc + PctPopUnderPov + PctNotHSGrad + PctEmplProfServ + MalePctDivorce + PctWorkMom + PctIlleg + PctImmigRec5 + PctImmigRec8 + PersPerOccupHous + PersPerRentOccHous + PctPersOwnOccup + PctHousOwnOcc + PctHousOccup + PctVacantBoarded + PctVacMore6Mos + RentLowQ + MedRent + MedOwnCostPctIncNoMtg + NumStreet, d_cleaned) 



summary(best.model2)
```
zczdfsf